add

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,7 +58,7 @@ jobs:
         id : lab1_points
         run: |
             qemu-system-riscv64 --version
-            # 必须刷新cargo ,不然shell里面调用cargo 会提前结束
+
             export PATH="$HOME/.cargo/bin:$PATH"
             source $HOME/.cargo/env
 
@@ -66,16 +66,14 @@ jobs:
 
             ./verify_lab1.sh > tmpa.txt
 
-            lab1_score=$(grep "Indicator:" tmpa.txt | tail -n1 | sed -E 's/.*Indicator: ([0-9]+).*/\1/' | grep -oE '[0-9]+')
+            lab1_score=$(grep "Indicator:" tmpa.txt | tail -n1 | sed -E 's/.*Indicator: *([0-9]+).*/\1/' || echo 0)
             
-            lab1_score=${lab1_score:-0}
-
             cat tmpa.txt
 
             echo "lab1_points=$lab1_score" 
-            rm tmpa.txt -f
             echo "lab1_points=$lab1_score" >>"$GITHUB_OUTPUT"
-
+            rm tmpa.txt -f
+            
   deploy:
     if: github.repository != 'arceos-org/oscamp'
     name: Report Score to Server
@@ -121,8 +119,9 @@ jobs:
             -s)
 
            if echo "$response" | grep -q '"result":1'; then
-             echo "成功：测试数据已发送"
+             echo "Success: Score submitted"
            else
-             echo "失败：接口返回异常"
+             echo "Error: API submission failed"
+            echo "$response"
              exit 1
            fi
